import type {
  University,
  Scholarship,
  SuccessStory,
  Professor,
  DomesticUniversity,
  IndianScholarship,
} from './types'

export const universities: University[] = [
  {
    id: '1',
    name: 'Massachusetts Institute of Technology',
    country: 'US',
    city: 'Cambridge, MA',
    ranking: 1,
    avgGRE: 332,
    avgCGPA: 9.2,
    tuitionUSD: 58240,
    program: 'MS Computer Science',
    acceptanceRate: 3.5,
    description: 'MIT\'s EECS department is the world leader in CS research with cutting-edge labs in AI, robotics, and quantum computing.',
    avgSalaryUSD: 165000,
    programDuration: 2,
  },
  {
    id: '2',
    name: 'Stanford University',
    country: 'US',
    city: 'Stanford, CA',
    ranking: 3,
    avgGRE: 330,
    avgCGPA: 9.0,
    tuitionUSD: 57861,
    program: 'MS Computer Science',
    acceptanceRate: 5.2,
    description: 'Stanford CS sits at the heart of Silicon Valley, offering unmatched access to tech companies and startup ecosystems.',
    avgSalaryUSD: 170000,
    programDuration: 2,
  },
  {
    id: '3',
    name: 'Carnegie Mellon University',
    country: 'US',
    city: 'Pittsburgh, PA',
    ranking: 5,
    avgGRE: 328,
    avgCGPA: 8.8,
    tuitionUSD: 52952,
    program: 'MS Computer Science',
    acceptanceRate: 7.5,
    description: 'CMU\'s School of Computer Science is a top destination for AI/ML, with faculty who pioneered the field.',
    avgSalaryUSD: 155000,
    programDuration: 2,
  },
  {
    id: '4',
    name: 'University of California, Berkeley',
    country: 'US',
    city: 'Berkeley, CA',
    ranking: 8,
    avgGRE: 326,
    avgCGPA: 8.5,
    tuitionUSD: 32756,
    program: 'MS EECS',
    acceptanceRate: 8.0,
    description: 'UC Berkeley EECS combines world-class research with proximity to Silicon Valley tech hubs.',
    avgSalaryUSD: 160000,
    programDuration: 2,
  },
  {
    id: '5',
    name: 'Georgia Institute of Technology',
    country: 'US',
    city: 'Atlanta, GA',
    ranking: 15,
    avgGRE: 322,
    avgCGPA: 8.2,
    tuitionUSD: 32404,
    program: 'MS Computer Science',
    acceptanceRate: 12.0,
    description: 'Georgia Tech offers one of the best value MS CS programs with multiple specialization tracks.',
    avgSalaryUSD: 130000,
    programDuration: 2,
  },
  {
    id: '6',
    name: 'University of Illinois Urbana-Champaign',
    country: 'US',
    city: 'Champaign, IL',
    ranking: 12,
    avgGRE: 324,
    avgCGPA: 8.3,
    tuitionUSD: 36086,
    program: 'MS Computer Science',
    acceptanceRate: 10.0,
    description: 'UIUC CS is consistently ranked top 5, with strong research in systems, databases, and AI.',
    avgSalaryUSD: 140000,
    programDuration: 2,
  },
  {
    id: '7',
    name: 'University of Toronto',
    country: 'Canada',
    city: 'Toronto, ON',
    ranking: 18,
    avgGRE: 320,
    avgCGPA: 8.0,
    tuitionUSD: 28500,
    program: 'MSc Computer Science',
    acceptanceRate: 15.0,
    description: 'UofT is the birthplace of deep learning, home to Geoffrey Hinton\'s team and the Vector Institute.',
    avgSalaryUSD: 95000,
    programDuration: 2,
  },
  {
    id: '8',
    name: 'University of British Columbia',
    country: 'Canada',
    city: 'Vancouver, BC',
    ranking: 35,
    avgGRE: 316,
    avgCGPA: 7.8,
    tuitionUSD: 22000,
    program: 'MSc Computer Science',
    acceptanceRate: 18.0,
    description: 'UBC combines strong CS research with Vancouver\'s growing tech scene and quality of life.',
    avgSalaryUSD: 85000,
    programDuration: 2,
  },
  {
    id: '9',
    name: 'Imperial College London',
    country: 'UK',
    city: 'London',
    ranking: 6,
    avgGRE: 325,
    avgCGPA: 8.5,
    tuitionUSD: 42500,
    program: 'MSc Computing',
    acceptanceRate: 12.0,
    description: 'Imperial College is London\'s top STEM university with deep industry connections in fintech and AI.',
    avgSalaryUSD: 85000,
    programDuration: 1,
  },
  {
    id: '10',
    name: 'University of Oxford',
    country: 'UK',
    city: 'Oxford',
    ranking: 4,
    avgGRE: 328,
    avgCGPA: 8.8,
    tuitionUSD: 45000,
    program: 'MSc Computer Science',
    acceptanceRate: 8.0,
    description: 'Oxford CS combines centuries of academic tradition with cutting-edge research in AI safety and ML.',
    avgSalaryUSD: 90000,
    programDuration: 1,
  },
  {
    id: '11',
    name: 'ETH Zurich',
    country: 'Switzerland',
    city: 'Zurich',
    ranking: 7,
    avgGRE: 326,
    avgCGPA: 8.5,
    tuitionUSD: 1500,
    program: 'MSc Computer Science',
    acceptanceRate: 15.0,
    description: 'ETH Zurich offers world-class CS education at incredibly low tuition, with strong ties to Swiss industry.',
    avgSalaryUSD: 110000,
    programDuration: 2,
  },
  {
    id: '12',
    name: 'Technical University of Munich',
    country: 'Germany',
    city: 'Munich',
    ranking: 25,
    avgGRE: 318,
    avgCGPA: 7.5,
    tuitionUSD: 300,
    program: 'MSc Informatics',
    acceptanceRate: 20.0,
    description: 'TUM is Germany\'s top tech university with virtually free tuition and strong automotive/industry connections.',
    avgSalaryUSD: 75000,
    programDuration: 2,
  },
  {
    id: '13',
    name: 'University of Melbourne',
    country: 'Australia',
    city: 'Melbourne',
    ranking: 28,
    avgGRE: 315,
    avgCGPA: 7.5,
    tuitionUSD: 35000,
    program: 'Master of IT',
    acceptanceRate: 25.0,
    description: 'Melbourne offers top-ranked tech programs with excellent post-study work rights in Australia.',
    avgSalaryUSD: 80000,
    programDuration: 2,
  },
  {
    id: '14',
    name: 'National University of Singapore',
    country: 'Singapore',
    city: 'Singapore',
    ranking: 11,
    avgGRE: 322,
    avgCGPA: 8.2,
    tuitionUSD: 25000,
    program: 'MSc Computer Science',
    acceptanceRate: 15.0,
    description: 'NUS is Asia\'s top CS program with strong connections to Singapore\'s booming tech ecosystem.',
    avgSalaryUSD: 85000,
    programDuration: 1.5,
  },
  {
    id: '15',
    name: 'IIM Ahmedabad',
    country: 'India',
    city: 'Ahmedabad',
    ranking: 1,
    avgGRE: 0,
    avgCGPA: 8.5,
    tuitionUSD: 28000,
    program: 'PGP (MBA)',
    acceptanceRate: 2.0,
    description: 'India\'s premier management institute with the highest ROI MBA in Asia.',
    avgSalaryUSD: 45000,
    programDuration: 2,
  },
  {
    id: '16',
    name: 'ISB Hyderabad',
    country: 'India',
    city: 'Hyderabad',
    ranking: 3,
    avgGRE: 0,
    avgCGPA: 7.5,
    tuitionUSD: 42000,
    program: 'PGP (MBA)',
    acceptanceRate: 10.0,
    description: 'ISB\'s 1-year MBA offers fast-track career acceleration with strong global placements.',
    avgSalaryUSD: 40000,
    programDuration: 1,
  },
  {
    id: '17',
    name: 'University of Waterloo',
    country: 'Canada',
    city: 'Waterloo, ON',
    ranking: 30,
    avgGRE: 318,
    avgCGPA: 7.8,
    tuitionUSD: 20000,
    program: 'MMath Computer Science',
    acceptanceRate: 20.0,
    description: 'Waterloo is famous for its co-op programs and strong pipeline to Silicon Valley companies.',
    avgSalaryUSD: 90000,
    programDuration: 2,
  },
  {
    id: '18',
    name: 'University of Edinburgh',
    country: 'UK',
    city: 'Edinburgh',
    ranking: 20,
    avgGRE: 320,
    avgCGPA: 8.0,
    tuitionUSD: 38000,
    program: 'MSc AI',
    acceptanceRate: 15.0,
    description: 'Edinburgh\'s School of Informatics is the largest in the UK with a strong focus on AI and NLP.',
    avgSalaryUSD: 80000,
    programDuration: 1,
  },
  {
    id: '19',
    name: 'University of Michigan',
    country: 'US',
    city: 'Ann Arbor, MI',
    ranking: 10,
    avgGRE: 325,
    avgCGPA: 8.5,
    tuitionUSD: 51174,
    program: 'MS CSE',
    acceptanceRate: 9.0,
    description: 'UMich CSE offers exceptional research opportunities with strong industry recruiting.',
    avgSalaryUSD: 145000,
    programDuration: 2,
  },
  {
    id: '20',
    name: 'University of Texas at Austin',
    country: 'US',
    city: 'Austin, TX',
    ranking: 14,
    avgGRE: 323,
    avgCGPA: 8.3,
    tuitionUSD: 30116,
    program: 'MS Computer Science',
    acceptanceRate: 11.0,
    description: 'UT Austin CS is rising fast with Austin\'s tech boom attracting top faculty and companies.',
    avgSalaryUSD: 140000,
    programDuration: 2,
  },
]

export const scholarships: Scholarship[] = [
  {
    id: '1',
    name: 'Fulbright-Nehru Master\'s Fellowship',
    provider: 'USIEF',
    amount: 3500000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-05-15',
    eligibility: 'Indian citizen, CGPA > 7.5, work experience preferred',
    matchScore: 85,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '2',
    name: 'Chevening Scholarship',
    provider: 'UK Government',
    amount: 4000000,
    currency: 'INR',
    country: 'UK',
    deadline: '2026-11-01',
    eligibility: 'Min 2 years work exp, return to India commitment',
    matchScore: 78,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '3',
    name: 'DAAD Scholarship',
    provider: 'German Government',
    amount: 1800000,
    currency: 'INR',
    country: 'Germany',
    deadline: '2026-10-15',
    eligibility: 'Bachelor\'s degree, strong academics',
    matchScore: 72,
    field: 'STEM',
    type: 'Merit',
  },
  {
    id: '4',
    name: 'Rotary Peace Fellowship',
    provider: 'Rotary Foundation',
    amount: 5000000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-05-31',
    eligibility: 'Strong leadership, community service',
    matchScore: 65,
    field: 'Peace Studies',
    type: 'Need',
  },
  {
    id: '5',
    name: 'Commonwealth Scholarship',
    provider: 'CSC UK',
    amount: 3500000,
    currency: 'INR',
    country: 'UK',
    deadline: '2026-12-20',
    eligibility: 'Citizen of Commonwealth country, strong academic record',
    matchScore: 80,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '6',
    name: 'Stanford Knight-Hennessy Scholarship',
    provider: 'Stanford University',
    amount: 8000000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-10-12',
    eligibility: 'Exceptional leadership, civic commitment',
    matchScore: 55,
    field: 'All Fields',
    type: 'Merit',
  },
  {
    id: '7',
    name: 'Vanier Canada Graduate Scholarship',
    provider: 'Canadian Government',
    amount: 4200000,
    currency: 'INR',
    country: 'Canada',
    deadline: '2026-11-01',
    eligibility: 'PhD applicants, academic excellence + leadership',
    matchScore: 60,
    field: 'All Fields',
    type: 'Research',
  },
  {
    id: '8',
    name: 'Australia Awards Scholarship',
    provider: 'Australian Government',
    amount: 5000000,
    currency: 'INR',
    country: 'Australia',
    deadline: '2026-04-30',
    eligibility: 'Developing country citizen, return home commitment',
    matchScore: 75,
    field: 'All Fields',
    type: 'Need',
  },
  {
    id: '9',
    name: 'Erasmus Mundus Joint Master',
    provider: 'European Union',
    amount: 3000000,
    currency: 'INR',
    country: 'Europe',
    deadline: '2026-01-15',
    eligibility: 'Bachelor\'s degree, strong academics',
    matchScore: 70,
    field: 'Engineering',
    type: 'Merit',
  },
  {
    id: '10',
    name: 'Inlaks Shivdasani Foundation Scholarship',
    provider: 'Inlaks Foundation',
    amount: 6000000,
    currency: 'INR',
    country: 'US',
    deadline: '2026-04-20',
    eligibility: 'Indian national, under 30, exceptional academics',
    matchScore: 68,
    field: 'All Fields',
    type: 'Merit',
  },
]

export const successStories: SuccessStory[] = [
  {
    id: '1',
    anonymizedName: 'Student A',
    backgroundUniversity: 'BITS Pilani',
    cgpa: 7.8,
    greScore: 322,
    workExp: 2,
    targetUniversity: 'Carnegie Mellon University',
    targetCountry: 'US',
    program: 'MS Computer Science',
    loanAmount: 5500000,
    nbfc: 'Avanse Financial',
    currentSalaryUSD: 155000,
    yearOfAdmission: 2022,
    avatar: '🧑‍💻',
  },
  {
    id: '2',
    anonymizedName: 'Student B',
    backgroundUniversity: 'VIT Vellore',
    cgpa: 8.2,
    greScore: 318,
    workExp: 1,
    targetUniversity: 'Georgia Institute of Technology',
    targetCountry: 'US',
    program: 'MS Computer Science',
    loanAmount: 4500000,
    nbfc: 'HDFC Credila',
    currentSalaryUSD: 135000,
    yearOfAdmission: 2023,
    avatar: '👩‍💻',
  },
  {
    id: '3',
    anonymizedName: 'Student C',
    backgroundUniversity: 'NIT Trichy',
    cgpa: 8.8,
    greScore: 328,
    workExp: 3,
    targetUniversity: 'Stanford University',
    targetCountry: 'US',
    program: 'MS Computer Science',
    loanAmount: 7500000,
    nbfc: 'Auxilo Finserve',
    currentSalaryUSD: 185000,
    yearOfAdmission: 2021,
    avatar: '🧑‍🎓',
  },
  {
    id: '4',
    anonymizedName: 'Student D',
    backgroundUniversity: 'IIIT Hyderabad',
    cgpa: 9.0,
    greScore: 330,
    workExp: 0,
    targetUniversity: 'University of Toronto',
    targetCountry: 'Canada',
    program: 'MSc Computer Science',
    loanAmount: 3500000,
    nbfc: 'MPOWER Financing',
    currentSalaryUSD: 105000,
    yearOfAdmission: 2023,
    avatar: '👨‍🔬',
  },
  {
    id: '5',
    anonymizedName: 'Student E',
    backgroundUniversity: 'DTU Delhi',
    cgpa: 7.5,
    greScore: 315,
    workExp: 4,
    targetUniversity: 'University of British Columbia',
    targetCountry: 'Canada',
    program: 'MSc Computer Science',
    loanAmount: 3000000,
    nbfc: 'Avanse Financial',
    currentSalaryUSD: 95000,
    yearOfAdmission: 2022,
    avatar: '👩‍🎓',
  },
  {
    id: '6',
    anonymizedName: 'Student F',
    backgroundUniversity: 'IIT Bombay',
    cgpa: 8.5,
    greScore: 326,
    workExp: 2,
    targetUniversity: 'ETH Zurich',
    targetCountry: 'Switzerland',
    program: 'MSc Computer Science',
    loanAmount: 1500000,
    nbfc: 'SBI Education Loan',
    currentSalaryUSD: 120000,
    yearOfAdmission: 2022,
    avatar: '🧑‍💼',
  },
  {
    id: '7',
    anonymizedName: 'Student G',
    backgroundUniversity: 'NSIT Delhi',
    cgpa: 7.2,
    greScore: 312,
    workExp: 3,
    targetUniversity: 'University of Melbourne',
    targetCountry: 'Australia',
    program: 'Master of IT',
    loanAmount: 4000000,
    nbfc: 'Auxilo Finserve',
    currentSalaryUSD: 85000,
    yearOfAdmission: 2023,
    avatar: '👨‍💻',
  },
  {
    id: '8',
    anonymizedName: 'Student H',
    backgroundUniversity: 'PEC Chandigarh',
    cgpa: 8.0,
    greScore: 320,
    workExp: 1,
    targetUniversity: 'Imperial College London',
    targetCountry: 'UK',
    program: 'MSc Computing',
    loanAmount: 5000000,
    nbfc: 'HDFC Credila',
    currentSalaryUSD: 90000,
    yearOfAdmission: 2023,
    avatar: '👩‍🔬',
  },
  {
    id: '9',
    anonymizedName: 'Student I',
    backgroundUniversity: 'COEP Pune',
    cgpa: 8.3,
    greScore: 325,
    workExp: 2,
    targetUniversity: 'University of Michigan',
    targetCountry: 'US',
    program: 'MS CSE',
    loanAmount: 6000000,
    nbfc: 'Avanse Financial',
    currentSalaryUSD: 150000,
    yearOfAdmission: 2022,
    avatar: '🧑‍🎓',
  },
  {
    id: '10',
    anonymizedName: 'Student J',
    backgroundUniversity: 'Manipal IT',
    cgpa: 7.6,
    greScore: 316,
    workExp: 5,
    targetUniversity: 'ISB Hyderabad',
    targetCountry: 'India',
    program: 'PGP (MBA)',
    loanAmount: 3500000,
    nbfc: 'HDFC Credila',
    currentSalaryUSD: 42000,
    yearOfAdmission: 2023,
    avatar: '👨‍🎓',
  },
]

export const professors: Professor[] = [
  {
    id: '1',
    name: 'Dr. Andrew Ng',
    university: 'Stanford University',
    department: 'Computer Science',
    researchAreas: ['Machine Learning', 'Deep Learning', 'AI Education'],
    email: 'ang@stanford.edu',
    hIndex: 168,
    recentPapers: ['Scaling instruction-tuned LLMs', 'Data-centric AI'],
  },
  {
    id: '2',
    name: 'Dr. Yann LeCun',
    university: 'New York University',
    department: 'Computer Science',
    researchAreas: ['Deep Learning', 'Computer Vision', 'Self-supervised Learning'],
    email: 'yann@cs.nyu.edu',
    hIndex: 155,
    recentPapers: ['A Path Towards Autonomous AI', 'V-JEPA'],
  },
  {
    id: '3',
    name: 'Dr. Fei-Fei Li',
    university: 'Stanford University',
    department: 'Computer Science',
    researchAreas: ['Computer Vision', 'Cognitive Neuroscience', 'AI Healthcare'],
    email: 'feifeili@stanford.edu',
    hIndex: 142,
    recentPapers: ['Foundation Models for Robotics', 'World Labs vision'],
  },
  {
    id: '4',
    name: 'Dr. Yoshua Bengio',
    university: 'University of Montreal',
    department: 'Computer Science',
    researchAreas: ['Deep Learning', 'Generative Models', 'AI Safety'],
    email: 'yoshua.bengio@umontreal.ca',
    hIndex: 190,
    recentPapers: ['GFlowNets', 'Causal Representation Learning'],
  },
  {
    id: '5',
    name: 'Dr. Pushmeet Kohli',
    university: 'Google DeepMind',
    department: 'AI Research',
    researchAreas: ['AI for Science', 'Protein Structure', 'Reasoning'],
    email: 'pushmeet@google.com',
    hIndex: 85,
    recentPapers: ['AlphaFold extensions', 'Mathematical reasoning'],
  },
  {
    id: '6',
    name: 'Dr. Percy Liang',
    university: 'Stanford University',
    department: 'Computer Science',
    researchAreas: ['NLP', 'Foundation Models', 'AI Evaluation'],
    email: 'pliang@stanford.edu',
    hIndex: 78,
    recentPapers: ['HELM benchmark', 'Foundation model transparency'],
  },
  {
    id: '7',
    name: 'Dr. Raquel Urtasun',
    university: 'University of Toronto',
    department: 'Computer Science',
    researchAreas: ['Autonomous Driving', 'Computer Vision', '3D Perception'],
    email: 'urtasun@cs.toronto.edu',
    hIndex: 92,
    recentPapers: ['Neural scene representations', 'Waabi world model'],
  },
  {
    id: '8',
    name: 'Dr. Anima Anandkumar',
    university: 'Caltech',
    department: 'Computing + Mathematical Sciences',
    researchAreas: ['Tensor Methods', 'Physics-informed AI', 'Scientific Computing'],
    email: 'anima@caltech.edu',
    hIndex: 75,
    recentPapers: ['Neural operators for PDEs', 'FourCastNet'],
  },
  {
    id: '9',
    name: 'Dr. Srinivasan Keshav',
    university: 'University of Cambridge',
    department: 'Computer Science',
    researchAreas: ['Computer Networks', 'Energy Systems', 'Sustainability'],
    email: 'sk818@cam.ac.uk',
    hIndex: 68,
    recentPapers: ['Carbon-aware computing', 'Grid-interactive buildings'],
  },
  {
    id: '10',
    name: 'Dr. Subhash Khot',
    university: 'New York University',
    department: 'Computer Science',
    researchAreas: ['Computational Complexity', 'Approximation Algorithms', 'Theoretical CS'],
    email: 'khot@cs.nyu.edu',
    hIndex: 42,
    recentPapers: ['Unique Games Conjecture progress', 'Hardness of approximation'],
  },
]

export const livingCostData: Record<string, { rent: number; food: number; transport: number; utilities: number; entertainment: number; currency: string }> = {
  'Mumbai': { rent: 25000, food: 12000, transport: 3000, utilities: 3000, entertainment: 5000, currency: 'INR' },
  'Delhi': { rent: 20000, food: 10000, transport: 2500, utilities: 2500, entertainment: 4000, currency: 'INR' },
  'Bangalore': { rent: 22000, food: 11000, transport: 2000, utilities: 2800, entertainment: 4500, currency: 'INR' },
  'Pune': { rent: 15000, food: 8000, transport: 1500, utilities: 2000, entertainment: 3500, currency: 'INR' },
  'Boston': { rent: 210000, food: 50000, transport: 12000, utilities: 15000, entertainment: 20000, currency: 'INR' },
  'San Francisco': { rent: 280000, food: 55000, transport: 10000, utilities: 12000, entertainment: 25000, currency: 'INR' },
  'New York': { rent: 260000, food: 55000, transport: 15000, utilities: 13000, entertainment: 25000, currency: 'INR' },
  'London': { rent: 230000, food: 45000, transport: 18000, utilities: 14000, entertainment: 20000, currency: 'INR' },
  'Toronto': { rent: 180000, food: 40000, transport: 10000, utilities: 12000, entertainment: 15000, currency: 'INR' },
  'Vancouver': { rent: 190000, food: 42000, transport: 9000, utilities: 11000, entertainment: 16000, currency: 'INR' },
  'Melbourne': { rent: 160000, food: 38000, transport: 10000, utilities: 10000, entertainment: 14000, currency: 'INR' },
  'Zurich': { rent: 250000, food: 60000, transport: 12000, utilities: 15000, entertainment: 20000, currency: 'INR' },
  'Munich': { rent: 140000, food: 35000, transport: 8000, utilities: 10000, entertainment: 12000, currency: 'INR' },
  'Singapore': { rent: 200000, food: 40000, transport: 8000, utilities: 10000, entertainment: 18000, currency: 'INR' },
  'Pittsburgh': { rent: 120000, food: 35000, transport: 7000, utilities: 10000, entertainment: 10000, currency: 'INR' },
  'Austin': { rent: 150000, food: 38000, transport: 8000, utilities: 11000, entertainment: 15000, currency: 'INR' },
}

// ─────────────────────────────────────────────────────────────────────────────
// Domestic Track MVP — additive datasets
// Source of truth: .kiro/specs/domestic-track-mvp/design.md → "Sample
// Domestic_Universities_Dataset records", "Premier_Institute_List", and
// "Scholarship Hunter Currency-Based Default".
// These exports are additive; nothing above this section was modified.
// ─────────────────────────────────────────────────────────────────────────────

export const domesticUniversities: DomesticUniversity[] = [
  // ── IITs (B.Tech CSE) — JEE_Advanced, CSIS-notified ──
  {
    id: 'iitb-cse',
    name: 'IIT Bombay — CSE',
    location: 'Mumbai, Maharashtra',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 2500000,
    seatMatrix: { General: 60, 'OBC-NCL': 32, EWS: 12, SC: 18, ST: 9, PwD: 3 },
    closingRanks: { General: 68, 'OBC-NCL': 45, EWS: 39, SC: 28, ST: 12, PwD: 15 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iitd-cse',
    name: 'IIT Delhi — CSE',
    location: 'New Delhi, Delhi',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 2400000,
    seatMatrix: { General: 56, 'OBC-NCL': 30, EWS: 11, SC: 17, ST: 8, PwD: 3 },
    closingRanks: { General: 110, 'OBC-NCL': 65, EWS: 55, SC: 40, ST: 18, PwD: 20 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iitm-cse',
    name: 'IIT Madras — CSE',
    location: 'Chennai, Tamil Nadu',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 2300000,
    seatMatrix: { General: 54, 'OBC-NCL': 29, EWS: 11, SC: 16, ST: 8, PwD: 3 },
    closingRanks: { General: 165, 'OBC-NCL': 95, EWS: 80, SC: 55, ST: 22, PwD: 25 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iitkgp-cse',
    name: 'IIT Kharagpur — CSE',
    location: 'Kharagpur, West Bengal',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 2100000,
    seatMatrix: { General: 50, 'OBC-NCL': 27, EWS: 10, SC: 15, ST: 7, PwD: 3 },
    closingRanks: { General: 280, 'OBC-NCL': 140, EWS: 130, SC: 80, ST: 35, PwD: 40 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iitk-cse',
    name: 'IIT Kanpur — CSE',
    location: 'Kanpur, Uttar Pradesh',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 2200000,
    seatMatrix: { General: 50, 'OBC-NCL': 27, EWS: 10, SC: 15, ST: 7, PwD: 3 },
    closingRanks: { General: 220, 'OBC-NCL': 110, EWS: 105, SC: 65, ST: 28, PwD: 30 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iitr-cse',
    name: 'IIT Roorkee — CSE',
    location: 'Roorkee, Uttarakhand',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 2000000,
    seatMatrix: { General: 48, 'OBC-NCL': 26, EWS: 9, SC: 14, ST: 7, PwD: 3 },
    closingRanks: { General: 330, 'OBC-NCL': 165, EWS: 150, SC: 90, ST: 38, PwD: 45 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iit-bhu-cse',
    name: 'IIT BHU — CSE',
    location: 'Varanasi, Uttar Pradesh',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 1900000,
    seatMatrix: { General: 48, 'OBC-NCL': 25, EWS: 9, SC: 14, ST: 7, PwD: 3 },
    closingRanks: { General: 480, 'OBC-NCL': 240, EWS: 220, SC: 130, ST: 55, PwD: 60 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iit-guwahati-cse',
    name: 'IIT Guwahati — CSE',
    location: 'Guwahati, Assam',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 1950000,
    seatMatrix: { General: 46, 'OBC-NCL': 24, EWS: 9, SC: 13, ST: 7, PwD: 2 },
    closingRanks: { General: 420, 'OBC-NCL': 215, EWS: 195, SC: 115, ST: 48, PwD: 52 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iit-hyderabad-cse',
    name: 'IIT Hyderabad — CSE',
    location: 'Hyderabad, Telangana',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 2100000,
    seatMatrix: { General: 44, 'OBC-NCL': 23, EWS: 9, SC: 13, ST: 6, PwD: 2 },
    closingRanks: { General: 510, 'OBC-NCL': 260, EWS: 230, SC: 145, ST: 58, PwD: 65 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iit-indore-cse',
    name: 'IIT Indore — CSE',
    location: 'Indore, Madhya Pradesh',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 1700000,
    seatMatrix: { General: 36, 'OBC-NCL': 19, EWS: 7, SC: 11, ST: 5, PwD: 2 },
    closingRanks: { General: 880, 'OBC-NCL': 460, EWS: 410, SC: 270, ST: 95, PwD: 110 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iit-ropar-cse',
    name: 'IIT Ropar — CSE',
    location: 'Rupnagar, Punjab',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 1650000,
    seatMatrix: { General: 36, 'OBC-NCL': 19, EWS: 7, SC: 11, ST: 5, PwD: 2 },
    closingRanks: { General: 950, 'OBC-NCL': 510, EWS: 470, SC: 290, ST: 105, PwD: 120 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iit-mandi-cse',
    name: 'IIT Mandi — CSE',
    location: 'Mandi, Himachal Pradesh',
    examType: 'JEE_Advanced',
    tuitionINR: 250000,
    avgDomesticPlacementCtcINR: 1550000,
    seatMatrix: { General: 32, 'OBC-NCL': 17, EWS: 6, SC: 10, ST: 5, PwD: 2 },
    closingRanks: { General: 1450, 'OBC-NCL': 760, EWS: 680, SC: 410, ST: 145, PwD: 165 },
    isNotifiedForCSIS: true,
  },

  // ── IITs / IISc (M.Tech CSE) — GATE, CSIS-notified ──
  {
    id: 'iisc-mtech-cse',
    name: 'IISc Bengaluru — M.Tech CSE',
    location: 'Bengaluru, Karnataka',
    examType: 'GATE',
    tuitionINR: 50000,
    avgDomesticPlacementCtcINR: 3000000,
    seatMatrix: { General: 12, 'OBC-NCL': 6, EWS: 3, SC: 3, ST: 2, PwD: 1 },
    closingRanks: { General: 45, 'OBC-NCL': 120, EWS: 85, SC: 320, ST: 410, PwD: 250 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iitb-mtech-cse',
    name: 'IIT Bombay — M.Tech CSE',
    location: 'Mumbai, Maharashtra',
    examType: 'GATE',
    tuitionINR: 50000,
    avgDomesticPlacementCtcINR: 2700000,
    seatMatrix: { General: 24, 'OBC-NCL': 13, EWS: 5, SC: 7, ST: 3, PwD: 1 },
    closingRanks: { General: 95, 'OBC-NCL': 250, EWS: 175, SC: 580, ST: 720, PwD: 480 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iitd-mtech-cse',
    name: 'IIT Delhi — M.Tech CSE',
    location: 'New Delhi, Delhi',
    examType: 'GATE',
    tuitionINR: 50000,
    avgDomesticPlacementCtcINR: 2600000,
    seatMatrix: { General: 22, 'OBC-NCL': 12, EWS: 4, SC: 6, ST: 3, PwD: 1 },
    closingRanks: { General: 140, 'OBC-NCL': 360, EWS: 250, SC: 820, ST: 980, PwD: 650 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'nit-trichy-mtech-cse',
    name: 'NIT Trichy — M.Tech CSE',
    location: 'Tiruchirappalli, Tamil Nadu',
    examType: 'GATE',
    tuitionINR: 70000,
    avgDomesticPlacementCtcINR: 1400000,
    seatMatrix: { General: 18, 'OBC-NCL': 10, EWS: 4, SC: 5, ST: 3, PwD: 1 },
    closingRanks: { General: 1850, 'OBC-NCL': 4200, EWS: 3100, SC: 8500, ST: 11000, PwD: 6800 },
    isNotifiedForCSIS: true,
  },

  // ── NITs (B.Tech CSE) — JEE_Advanced (proxy field), CSIS-notified ──
  {
    id: 'nit-trichy-cse',
    name: 'NIT Trichy — CSE',
    location: 'Tiruchirappalli, Tamil Nadu',
    examType: 'JEE_Advanced',
    tuitionINR: 150000,
    avgDomesticPlacementCtcINR: 1800000,
    seatMatrix: { General: 46, 'OBC-NCL': 25, EWS: 9, SC: 14, ST: 7, PwD: 2 },
    closingRanks: { General: 1380, 'OBC-NCL': 800, EWS: 720, SC: 480, ST: 220, PwD: 250 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'nit-warangal-cse',
    name: 'NIT Warangal — CSE',
    location: 'Warangal, Telangana',
    examType: 'JEE_Advanced',
    tuitionINR: 150000,
    avgDomesticPlacementCtcINR: 1700000,
    seatMatrix: { General: 44, 'OBC-NCL': 24, EWS: 9, SC: 13, ST: 6, PwD: 2 },
    closingRanks: { General: 1620, 'OBC-NCL': 920, EWS: 850, SC: 540, ST: 250, PwD: 285 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'nit-surathkal-cse',
    name: 'NIT Surathkal — CSE',
    location: 'Mangalore, Karnataka',
    examType: 'JEE_Advanced',
    tuitionINR: 150000,
    avgDomesticPlacementCtcINR: 1650000,
    seatMatrix: { General: 42, 'OBC-NCL': 23, EWS: 8, SC: 12, ST: 6, PwD: 2 },
    closingRanks: { General: 1780, 'OBC-NCL': 990, EWS: 920, SC: 580, ST: 270, PwD: 310 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'nit-calicut-cse',
    name: 'NIT Calicut — CSE',
    location: 'Kozhikode, Kerala',
    examType: 'JEE_Advanced',
    tuitionINR: 150000,
    avgDomesticPlacementCtcINR: 1500000,
    seatMatrix: { General: 40, 'OBC-NCL': 22, EWS: 8, SC: 12, ST: 6, PwD: 2 },
    closingRanks: { General: 4200, 'OBC-NCL': 2400, EWS: 2100, SC: 1300, ST: 580, PwD: 680 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'nit-rourkela-cse',
    name: 'NIT Rourkela — CSE',
    location: 'Rourkela, Odisha',
    examType: 'JEE_Advanced',
    tuitionINR: 150000,
    avgDomesticPlacementCtcINR: 1450000,
    seatMatrix: { General: 38, 'OBC-NCL': 21, EWS: 8, SC: 11, ST: 5, PwD: 2 },
    closingRanks: { General: 5100, 'OBC-NCL': 2900, EWS: 2600, SC: 1600, ST: 720, PwD: 820 },
    isNotifiedForCSIS: true,
  },

  // ── IIITs (B.Tech CSE) — JEE_Advanced (proxy field), private/deemed ──
  {
    id: 'iiit-hyderabad-cse',
    name: 'IIIT Hyderabad — CSE',
    location: 'Hyderabad, Telangana',
    examType: 'JEE_Advanced',
    tuitionINR: 350000,
    avgDomesticPlacementCtcINR: 2800000,
    seatMatrix: { General: 70, 'OBC-NCL': 38, EWS: 14, SC: 21, ST: 10, PwD: 3 },
    closingRanks: { General: 700, 'OBC-NCL': 420, EWS: 380, SC: 240, ST: 110, PwD: 130 },
    isNotifiedForCSIS: false,
  },
  {
    id: 'iiit-bangalore-cse',
    name: 'IIIT Bangalore — CSE',
    location: 'Bengaluru, Karnataka',
    examType: 'JEE_Advanced',
    tuitionINR: 400000,
    avgDomesticPlacementCtcINR: 2200000,
    seatMatrix: { General: 60, 'OBC-NCL': 32, EWS: 12, SC: 18, ST: 9, PwD: 3 },
    closingRanks: { General: 6800, 'OBC-NCL': 3800, EWS: 3500, SC: 2200, ST: 980, PwD: 1100 },
    isNotifiedForCSIS: false,
  },

  // ── BITS campuses (B.E. CSE) — JEE_Advanced (proxy field), not CSIS-notified ──
  {
    id: 'bits-pilani-cse',
    name: 'BITS Pilani — CSE',
    location: 'Pilani, Rajasthan',
    examType: 'JEE_Advanced',
    tuitionINR: 500000,
    avgDomesticPlacementCtcINR: 2100000,
    seatMatrix: { General: 100, 'OBC-NCL': 0, EWS: 0, SC: 0, ST: 0, PwD: 3 },
    closingRanks: { General: 8500, 'OBC-NCL': 4800, EWS: 4200, SC: 2800, ST: 1300, PwD: 1500 },
    isNotifiedForCSIS: false,
  },
  {
    id: 'bits-hyderabad-cse',
    name: 'BITS Hyderabad — CSE',
    location: 'Hyderabad, Telangana',
    examType: 'JEE_Advanced',
    tuitionINR: 500000,
    avgDomesticPlacementCtcINR: 1850000,
    seatMatrix: { General: 90, 'OBC-NCL': 0, EWS: 0, SC: 0, ST: 0, PwD: 3 },
    closingRanks: { General: 14500, 'OBC-NCL': 8200, EWS: 7400, SC: 4800, ST: 2100, PwD: 2400 },
    isNotifiedForCSIS: false,
  },
  {
    id: 'bits-goa-cse',
    name: 'BITS Goa — CSE',
    location: 'Sancoale, Goa',
    examType: 'JEE_Advanced',
    tuitionINR: 500000,
    avgDomesticPlacementCtcINR: 1800000,
    seatMatrix: { General: 90, 'OBC-NCL': 0, EWS: 0, SC: 0, ST: 0, PwD: 3 },
    closingRanks: { General: 13800, 'OBC-NCL': 7800, EWS: 7100, SC: 4500, ST: 2000, PwD: 2300 },
    isNotifiedForCSIS: false,
  },

  // ── IIMs / ISB (PGP) — CAT, percentile-based closing ──
  {
    id: 'iim-a-pgp',
    name: 'IIM Ahmedabad — PGP',
    location: 'Ahmedabad, Gujarat',
    examType: 'CAT',
    tuitionINR: 2500000,
    avgDomesticPlacementCtcINR: 3400000,
    seatMatrix: { General: 200, 'OBC-NCL': 108, EWS: 40, SC: 60, ST: 30, PwD: 12 },
    closingRanks: { General: 99.5, 'OBC-NCL': 96.0, EWS: 97.5, SC: 80.0, ST: 65.0, PwD: 60.0 },
    isNotifiedForCSIS: false,
  },
  {
    id: 'iim-b-pgp',
    name: 'IIM Bangalore — PGP',
    location: 'Bengaluru, Karnataka',
    examType: 'CAT',
    tuitionINR: 2500000,
    avgDomesticPlacementCtcINR: 3300000,
    seatMatrix: { General: 195, 'OBC-NCL': 105, EWS: 39, SC: 58, ST: 29, PwD: 12 },
    closingRanks: { General: 99.3, 'OBC-NCL': 95.5, EWS: 96.5, SC: 78.0, ST: 63.0, PwD: 58.0 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iim-c-pgp',
    name: 'IIM Calcutta — PGP',
    location: 'Kolkata, West Bengal',
    examType: 'CAT',
    tuitionINR: 2500000,
    avgDomesticPlacementCtcINR: 3200000,
    seatMatrix: { General: 190, 'OBC-NCL': 102, EWS: 38, SC: 57, ST: 28, PwD: 11 },
    closingRanks: { General: 99.0, 'OBC-NCL': 95.0, EWS: 96.0, SC: 76.0, ST: 60.0, PwD: 55.0 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iim-l-pgp',
    name: 'IIM Lucknow — PGP',
    location: 'Lucknow, Uttar Pradesh',
    examType: 'CAT',
    tuitionINR: 2300000,
    avgDomesticPlacementCtcINR: 3000000,
    seatMatrix: { General: 180, 'OBC-NCL': 97, EWS: 36, SC: 54, ST: 27, PwD: 11 },
    closingRanks: { General: 97.5, 'OBC-NCL': 92.0, EWS: 93.5, SC: 72.0, ST: 58.0, PwD: 52.0 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iim-i-pgp',
    name: 'IIM Indore — PGP',
    location: 'Indore, Madhya Pradesh',
    examType: 'CAT',
    tuitionINR: 2200000,
    avgDomesticPlacementCtcINR: 2800000,
    seatMatrix: { General: 175, 'OBC-NCL': 94, EWS: 35, SC: 52, ST: 26, PwD: 10 },
    closingRanks: { General: 96.0, 'OBC-NCL': 90.0, EWS: 92.0, SC: 68.0, ST: 55.0, PwD: 50.0 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iim-k-pgp',
    name: 'IIM Kozhikode — PGP',
    location: 'Kozhikode, Kerala',
    examType: 'CAT',
    tuitionINR: 2200000,
    avgDomesticPlacementCtcINR: 2900000,
    seatMatrix: { General: 170, 'OBC-NCL': 91, EWS: 34, SC: 51, ST: 25, PwD: 10 },
    closingRanks: { General: 96.5, 'OBC-NCL': 91.0, EWS: 92.5, SC: 70.0, ST: 56.0, PwD: 51.0 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iim-shillong-pgp',
    name: 'IIM Shillong — PGP',
    location: 'Shillong, Meghalaya',
    examType: 'CAT',
    tuitionINR: 1900000,
    avgDomesticPlacementCtcINR: 2400000,
    seatMatrix: { General: 75, 'OBC-NCL': 40, EWS: 15, SC: 22, ST: 11, PwD: 4 },
    closingRanks: { General: 94.0, 'OBC-NCL': 87.0, EWS: 89.0, SC: 65.0, ST: 52.0, PwD: 48.0 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'iim-raipur-pgp',
    name: 'IIM Raipur — PGP',
    location: 'Raipur, Chhattisgarh',
    examType: 'CAT',
    tuitionINR: 1700000,
    avgDomesticPlacementCtcINR: 2200000,
    seatMatrix: { General: 90, 'OBC-NCL': 48, EWS: 18, SC: 27, ST: 13, PwD: 5 },
    closingRanks: { General: 93.5, 'OBC-NCL': 86.0, EWS: 88.0, SC: 64.0, ST: 51.0, PwD: 47.0 },
    isNotifiedForCSIS: true,
  },
  {
    id: 'isb-pgp',
    name: 'ISB Hyderabad — PGP',
    location: 'Hyderabad, Telangana',
    examType: 'CAT',
    tuitionINR: 3500000,
    avgDomesticPlacementCtcINR: 3500000,
    seatMatrix: { General: 480, 'OBC-NCL': 0, EWS: 0, SC: 0, ST: 0, PwD: 8 },
    closingRanks: { General: 85.0, 'OBC-NCL': 80.0, EWS: 82.0, SC: 60.0, ST: 50.0, PwD: 45.0 },
    isNotifiedForCSIS: false,
  },
]

export const premierInstituteList: string[] = [
  'iitb-cse', 'iitd-cse', 'iitm-cse', 'iitkgp-cse', 'iitk-cse', 'iitr-cse',
  'iisc-mtech-cse',
  'nit-trichy-cse', 'nit-warangal-cse', 'nit-surathkal-cse',
  'iiit-hyderabad-cse', 'iiit-bangalore-cse',
  'iim-a-pgp', 'iim-b-pgp', 'iim-c-pgp', 'iim-l-pgp', 'iim-i-pgp', 'iim-k-pgp',
  'isb-pgp',
  'bits-pilani-cse',
]

export const indianScholarships: IndianScholarship[] = [
  { id: 'inspire', name: 'INSPIRE Scholarship', provider: 'DST', amount: 80000, currency: 'INR', country: 'India', deadline: '2025-09-30', eligibility: 'Top 1% in Class XII Boards', matchScore: 90, field: 'Sciences', type: 'Merit' },
  { id: 'inspire-manak', name: 'INSPIRE-MANAK', provider: 'DST', amount: 10000, currency: 'INR', country: 'India', deadline: '2025-08-31', eligibility: 'Class 6-10 students', matchScore: 70, field: 'Sciences', type: 'Merit' },
  { id: 'reliance-ug', name: 'Reliance Foundation UG Scholarship', provider: 'Reliance Foundation', amount: 200000, currency: 'INR', country: 'India', deadline: '2025-10-15', eligibility: 'UG students', matchScore: 85, field: 'Any', type: 'Need' },
  { id: 'tata-trust', name: 'Tata Trust Scholarship', provider: 'Tata Trust', amount: 150000, currency: 'INR', country: 'India', deadline: '2025-11-01', eligibility: 'Need-based', matchScore: 80, field: 'Any', type: 'Need' },
  { id: 'mh-merit', name: 'Maharashtra State Merit Scholarship', provider: 'Govt of Maharashtra', amount: 50000, currency: 'INR', country: 'India', deadline: '2025-09-15', eligibility: 'MH-domicile UG/PG', matchScore: 75, field: 'Any', type: 'Merit' },
  { id: 'aicte-pragati', name: 'AICTE Pragati Scholarship', provider: 'AICTE', amount: 50000, currency: 'INR', country: 'India', deadline: '2025-10-31', eligibility: 'Women in technical education, family income < ₹8L', matchScore: 78, field: 'Engineering', type: 'Diversity' },
  { id: 'aicte-saksham', name: 'AICTE Saksham Scholarship', provider: 'AICTE', amount: 50000, currency: 'INR', country: 'India', deadline: '2025-10-31', eligibility: 'Differently abled UG/PG students in AICTE-approved programs', matchScore: 72, field: 'Engineering', type: 'Diversity' },
  { id: 'kvpy-sa', name: 'KVPY-SA Fellowship (Legacy)', provider: 'IISc / DST', amount: 84000, currency: 'INR', country: 'India', deadline: '2026-01-15', eligibility: 'Class XI science students with research aptitude', matchScore: 82, field: 'Sciences', type: 'Research' },
  { id: 'kvpy-sx', name: 'Kishore Vaigyanik Protsahan Yojana — SX (Legacy)', provider: 'IISc / DST', amount: 96000, currency: 'INR', country: 'India', deadline: '2026-02-10', eligibility: 'Class XII / 1st year UG science students', matchScore: 80, field: 'Sciences', type: 'Research' },
]
